AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: |
  Hae käyttäjän opinto-oikeudet henkilötunnuksella

Resources:
  OpintoOikeudet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist.zip
      Handler: Lambda.opintoOikeusHandler
      Runtime: nodejs20.x
      Timeout: 20
      MemorySize: 512
      Events:
        ListCustomers:
          Type: Api
          Properties:
            Path: /
            Method: POST
  WSDL:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist.zip
      Handler: Lambda.opintoOikeusHandler
      Runtime: nodejs20.x
      Timeout: 20
      MemorySize: 512
      Events:
        ListCustomers:
          Type: Api
          Properties:
            Path: /
            Method: GET
