AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: |
  Hae käyttäjän opinto-oikeudet henkilötunnuksella

Resources:
  OpintoOikeudet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Runtime: nodejs6.10
      Handler: lambda.hellohandler
      Events:
        ListCustomers:
          Type: Api
          Properties:
            Path: /
            Method: POST
