AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: |
  Hae käyttäjän opinto-oikeudet henkilötunnuksella

Resources:
  OpintoOikeudet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Runtime: nodejs12.x
      Timeout: 8
      Handler: Lambda.opintoOikeusHandler
      Events:
        ListCustomers:
          Type: Api
          Properties:
            Path: /
            Method: POST
  WSDL:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Runtime: nodejs12.x
      Timeout: 8
      Handler: Lambda.opintoOikeusHandler
      Events:
        ListCustomers:
          Type: Api
          Properties:
            Path: /
            Method: GET
