name: Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (dev/qa/prod)"
        required: true
        default: "dev"
      commithash:
        description: "Commit hash to deploy from"

jobs:
  deploy:
    name: Deploy
    environment:
      name: ${{ github.event.inputs.environment }}
    env:
      ENV_NAME: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.commithash }}

      - name: Setup Node 12
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: sam cli
        uses: tkt-actions/aws-sam-cli@v1
        with:
          cmd: sam --version

      - name: Assume role for target environment
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE }}
          role-duration-seconds: 3600
          role-session-name: Koski-mydata-Deployment-${{ github.event.inputs.commithash }}

      - name: Deploy
        run: |
          ./deploy-$ENV_NAME.sh
