name: Run tests
on:
  push:
    branches-ignore:
      - "master"
  pull_request:
env:
  DOCKER_BUILDKIT: 1
jobs:
  oma_opintopolku_loki_frontend:
    name: oma-opintopolku-loki frontend
    runs-on: ubuntu-20.04
    env:
      TEST_PORT: 3030
      TZ: Europe/Helsinki
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node 12
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Setup sam cli
        uses: tkt-actions/aws-sam-cli@v1
        with:
          cmd: sam --version

      - name: Run tests
        run: |
          npm install
          npm run build
